if(EXISTS "/Users/adriandiaconescu/CLionProjects/market-data-processor/build-asan-new/tests/unit_tests[1]_tests.cmake")
  include("/Users/adriandiaconescu/CLionProjects/market-data-processor/build-asan-new/tests/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
